# Site settings
title: Mark Drew on code
header-img: img/header-home.jpg
email: mark.drew@gmail.com
copyright_name: Mark Drew
description: "a compendium of cfml and web technology topics"
baseurl: ""
url: "http://markdrew.io"
twitter_username: markdrew
github_username:  cybersonic
email_username:  mark.drew@gmail.com
mastodon_url: https://mastodon.social/@markdrew
# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
disqus-account: markdrewblog
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

plugins: [jekyll-paginate, jekyll-feed]
