services:
  eleventy:
    image: node:18-alpine
    working_dir: /app
    command: sh -c "npm install && npm run serve"
    ports:
      - 3001:8080
    volumes:
      - .:/app
      - /app/node_modules
